[build]
  command = "yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "22.x"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "yarn dev"
  port = 5173